/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSchema: {
            id: string;
            name: string;
        };
        GameScheme: {
            current_player: {
                id: string;
                name: string;
            };
            board: ("X" | "O" | ".")[][];
        };
        TurnScheme: {
            x: string | number;
            y: string | number;
        };
        /** @enum {string} */
        RolesSchema: "Cross" | "Circles" | "Spectator";
        /** @enum {string} */
        RoomState: "Waiting" | "Playing";
        RoomSchema: {
            id: string;
            owner: {
                id: string;
                name: string;
            };
            name: string;
            users: {
                id: string;
                name: string;
            }[];
            crosses?: {
                id: string;
                name: string;
            };
            circles?: {
                id: string;
                name: string;
            };
            /** @enum {string} */
            state: "Waiting" | "Playing";
        };
        /** @enum {string} */
        Command: "join" | "rename" | "create" | "mark" | "claim" | "leave" | "rematch";
        CommandPayload: {
            /** @enum {string} */
            command: "join" | "rename" | "create" | "mark" | "claim" | "leave" | "rematch";
            payload: {
                name?: string;
                room?: string;
                target?: string;
                text?: string;
                /** @enum {string} */
                role?: "Cross" | "Circles" | "Spectator";
                cords?: {
                    x: string | number;
                    y: string | number;
                };
            };
        };
        MessageSchema: {
            /** @enum {string} */
            type: "connection" | "game" | "rename" | "join" | "rooms" | "users" | "room";
            data: {
                new_name?: string;
                connection_id?: string;
                room?: {
                    id: string;
                    owner: {
                        id: string;
                        name: string;
                    };
                    name: string;
                    users: {
                        id: string;
                        name: string;
                    }[];
                    crosses?: {
                        id: string;
                        name: string;
                    };
                    circles?: {
                        id: string;
                        name: string;
                    };
                    /** @enum {string} */
                    state: "Waiting" | "Playing";
                };
                rooms?: {
                    id: string;
                    owner: {
                        id: string;
                        name: string;
                    };
                    name: string;
                    users: {
                        id: string;
                        name: string;
                    }[];
                    crosses?: {
                        id: string;
                        name: string;
                    };
                    circles?: {
                        id: string;
                        name: string;
                    };
                    /** @enum {string} */
                    state: "Waiting" | "Playing";
                }[];
                room_id?: string;
                users_count?: number;
                /** @enum {string} */
                role?: "Cross" | "Circles" | "Spectator";
                game?: {
                    current_player: {
                        id: string;
                        name: string;
                    };
                    board: ("X" | "O" | ".")[][];
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
