/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSchema: {
            id: string;
            name: string;
        };
        /** @enum {string} */
        Command: "join" | "create" | "mark" | "leave" | "rematch";
        CommandPayload: {
            /** @enum {string} */
            command: "join" | "create" | "mark" | "leave" | "rematch";
            payload: {
                name?: string;
                room?: string;
                target?: string;
                text?: string;
            };
        };
        RoomSchema: {
            id: string;
            name: string;
            users: {
                id: string;
                name: string;
            }[];
        };
        MessageSchema: {
            /** @enum {string} */
            type: "connection" | "join" | "rooms" | "users" | "room";
            data: {
                connection_id?: string;
                room?: {
                    id: string;
                    name: string;
                    users: {
                        id: string;
                        name: string;
                    }[];
                };
                rooms?: {
                    id: string;
                    name: string;
                    users: {
                        id: string;
                        name: string;
                    }[];
                }[];
                room_id?: string;
                users_count?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
