/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/room/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiRoomAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSchema: {
            id: string;
            name: string;
        };
        MessageSchema: {
            /** @enum {string} */
            type: "rooms" | "users" | "room";
            data: unknown;
        };
        RoomSchema: {
            id: string;
            name: string;
            users: {
                id: string;
                name: string;
            }[];
        };
        /** @enum {string} */
        Command: "join" | "mark" | "leave" | "rematch";
        CommandPayload: {
            /** @enum {string} */
            command: "join" | "mark" | "leave" | "rematch";
            payload: {
                room?: string;
                target?: string;
                text?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    postApiRoomAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                };
                "multipart/form-data": {
                    name: string;
                };
            };
        };
        responses: never;
    };
}
