import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../schema"; // generated by openapi-typescript

const client = createFetchClient<paths>({ baseUrl: "http://localhost:3000" });
export const $api = createClient(client);
