import { useEffect } from "react";
import type { components } from "../schema"; // generated by openapi-typescript

interface RoomCardProps {
  room: components["schemas"]["RoomSchema"];
  join: () => void;
}

export default function RoomCard({ room, join}: RoomCardProps) {
  useEffect(() => {
    console.log(room)
  })
  return (
    <div className="border">
      <p>{room.name}</p>
      <p>owner: {room.owner.name}</p>
      <p>users in: {room.users?.length}</p>
      <p>id: {room.id}</p>
        <button onClick={join}>join</button>
    </div>
  );
}
