
import type { components } from "../schema"; // generated by openapi-typescript

interface RoomCardProps{
  room: components["schemas"]["RoomSchema"];
}

export default function RoomCard({room} : RoomCardProps) {
  return (
    <div>
      <h2>{room.name}</h2>
      <h3>users in: {room.users.length}</h3>
      <p>id: {room.id}</p>
    </div>
  )
}
